"""add revoked token sessions

Revision ID: 0174c045dcb9
Revises: 6c6bc1946a69
Create Date: 2026-07-22 11:15:16.739882

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0174c045dcb9"
down_revision = "6c6bc1946a69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("revoked_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_revoked_tokens_session_id"),
            ["session_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("revoked_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revoked_tokens_session_id"))

    op.drop_table("revoked_tokens")
    # ### end Alembic commands ###
